### ISSUE TITLE
Try to resolve config path relative to tslint.json if config file not found.

### ISSUE THREAD

**Issue by ShiKaiWi** [prettier/tslint-plugin-prettier#285]
Say I have a project that contains both beckend service and web files and is organized like this:
```
├── backend
│   ├── api
│   ├── common
│   ├── hubpkg
│   ├── idgen
│   ├── jsonrpc
│   └── ws
└── web
    ├── build
    ├── config
    ├── images.d.ts
    ├── node_modules
    ├── package.json
    ├── src
    ├── tslint.json
    └── .prettierrc
```

And here is my `tslint.json`:
```
{
    ...
    "rules": {
        "prettier": [true, ".prettierrc"],
        ...
    }
}
```

And I use vscode to write both backend and web codes so my favorite working directory is the project root directory and then `tslint` will report error for failure to find the `.prettierrc` file (because my cwd is project root directory and `tslint` can't find file `/path_to_project/.prettierrc`).  Also I can't change the config path to `web/.prettierrc` because some team members(frontend developers) and ci for web part both prefer to work under `web` directory.

So how about supporting to resolve the config file relative to `tslint.json` if fail to find the config file?

**Comment by ikatyang** [comment]
It seems you don't need to specify the config file path? we search up the fs tree to find `.prettierrc` by default, which means that `web/.prettierrc` is used for files in `web` by default.

**Comment by ShiKaiWi** [comment]
Thanks for your immediate reply!
It works!
