### ISSUE TITLE
Is it possible to run prettier on save?

### ISSUE THREAD

**Issue by cmacdonnacha** [prettier/tslint-plugin-prettier#289]
Is it possible to run prettier on save in VS code using this? I don't want to have to also install the VS code extension.

**Comment by ikatyang** [comment]
You have to install either

- the TSLint extension or
- the Prettier extension (with `.pretterrc`).

**Comment by cmacdonnacha** [comment]
Thanks. Can you tell me, can I remove `.editorconfig` if I already have `.prettierc`?

**Comment by ikatyang** [comment]
Yes, you can.
