### ISSUE TITLE
when using space-before-function-paren , getting conflicted rules

### ISSUE THREAD

**Issue by horrylala** [prettier/tslint-plugin-prettier#296]
### Description:
When using *space-before-function-paren* , get conflicting rules.

My react component:
![image](https://user-images.githubusercontent.com/12706476/62529831-fe5f8980-b871-11e9-951e-f2a59d6a1fbe.png)
Got error:
![image](https://user-images.githubusercontent.com/12706476/62529893-20590c00-b872-11e9-8f29-1747354131e1.png)

After i remove the space between function name *ShopShow* and  parenthesis *()*，it got :
![image](https://user-images.githubusercontent.com/12706476/62530041-66ae6b00-b872-11e9-9b48-0473613b826a.png)

My configuration files:
```
{
    "defaultSeverity": "error",
    "extends": [
      "tslint:recommended",
      "tslint-eslint-rules",
      "tslint-react",
      "tslint-plugin-prettier",
      "tslint-config-prettier"
    ],
    "jsRules": {},
    "rules": {
      "trailing-comma": [true, {"multiline": "never", "singleline": "never"}],
      "arrow-parens": false,
      "space-before-function-paren": [true, "always"],
			"quotemark": false,
      "no-console": [false],
      "ter-indent": [true, 2, {"SwitchCase": true}],
      "prettier": [true, {"semi": false, "singleQuote":true}],
      },
      // ...
}
```

I read the documentation, and using *tslint-config-prettier* at the last line in *extends*.
### Expected
It could using *space-before-function-paren*  rules.

Thank you ,guys.

**Comment by ikatyang** [comment]
The `rules` field takes precedence over the `extends` field, see https://github.com/prettier/tslint-config-prettier/issues/280#issuecomment-468116804 for more info.

**Comment by horrylala** [comment]
Thanks , following your instruction, i did't get conflict error, *CREATE ANOTHER tslint.json FILE*.
But as i mentioned before , i just want to use *TSLINT* rules instead of *PRETTIER* rule *space-before-function-paren*, how should i do, any suggestion?

**Comment by ikatyang** [comment]
The only way to achieve this goal is to use `// tslint:disable-next-line`, but I guess that's probably not something you want. I'm afraid that there is probably no way to achieve it in an acceptable way as there is no such option in Prettier.
