### ISSUE TITLE
readme.md seems wrong about configuration

### ISSUE THREAD

**Issue by vincentpalita** [prettier/tslint-plugin-prettier#368]
The readme shows following configuration. It's in fact the opposite. Shall I open a pull request to fix that?

for tslint@^5.2.0
```
{
  "rulesDirectory": ["tslint-plugin-prettier"],
  "rules": {
    "prettier": true
  }
}
```

for tslint@^5.0.0
```
{
  "extends": ["tslint-plugin-prettier"],
  "rules": {
    "prettier": true
  }
}
```

**Comment by ikatyang** [comment]
What did you mean by _opposite_? The `rulesDirectory` field is preferred over `extends` but it only works for TSLint 5.2.0+.

**Comment by vincentpalita** [comment]
Well just tried it with tslint 6.1.1 and it didn't work until I put it in extends.

**Comment by ikatyang** [comment]
We use the same config in this repo:

https://github.com/prettier/tslint-plugin-prettier/blob/2bf510d58de76937d4d9953879e57b6c6fd7b9ae/package.json#L42
https://github.com/prettier/tslint-plugin-prettier/blob/2bf510d58de76937d4d9953879e57b6c6fd7b9ae/tslint.json#L2

I just tested it locally with `tslint-plugin-prettier@2.3.0` and it did work on my machine. Could you share some steps to reproduce?

**Comment by vincentpalita** [comment]
Well I am sorry for the trouble, I tried again after removing all node modules and it is working with rulesDirectory instead of extends.

Thanks for your help @ikatyang !
